module Verifrog.Runner.Codegen

open System
open System.IO
open System.Text
open System.Text.RegularExpressions
open Verifrog.Runner.Declarative

/// Sanitize a filename into a valid F# module name
let private toModuleName (fileName: string) =
    let base' = Path.GetFileNameWithoutExtension(fileName)
    let sanitized = Regex.Replace(base', @"[^a-zA-Z0-9_]", "_")
    // F# module names must start with uppercase letter
    let first = Char.ToUpperInvariant(sanitized.[0])
    string first + sanitized.[1..] + "_verifrog"

/// Render a Step value as an F# expression string
let private renderStep (step: Step) : string =
    let escStr (s: string) = s.Replace("\\", "\\\\").Replace("\"", "\\\"")
    match step with
    | Write (signal, value) ->
        $"""Write ("{escStr signal}", {value}L)"""
    | StepCycles count ->
        $"StepCycles {count}"
    | Expect (signal, op, value) ->
        $"""Expect ("{escStr signal}", "{escStr op}", {value}L)"""
    | ExpectMemory (memory, bank, addr, op, value) ->
        $"""ExpectMemory ("{escStr memory}", {bank}, {addr}, "{escStr op}", {value}L)"""
    | Load (memory, bank, data) ->
        let dataStr = data |> List.map (fun v -> $"{v}L") |> String.concat "; "
        $"""Load ("{escStr memory}", {bank}, [{dataStr}])"""
    | LoadFromFile (memory, bank, path) ->
        $"""LoadFromFile ("{escStr memory}", {bank}, "{escStr path}")"""
    | RunUntil (signal, value, max) ->
        $"""RunUntil ("{escStr signal}", {value}L, {max})"""
    | Force (signal, value) ->
        $"""Force ("{escStr signal}", {value}L)"""
    | Release signal ->
        $"""Release "{escStr signal}" """
    | Checkpoint name ->
        $"""Checkpoint "{escStr name}" """
    | Restore name ->
        $"""Restore "{escStr name}" """

/// Generate an F# source file from parsed .verifrog tests.
/// tomlAbsPath: absolute path to verifrog.toml
/// verifrogAbsPath: absolute path to the .verifrog file (used in #line directives)
/// tests: parsed DeclTest list
let generateTestFile (tomlAbsPath: string) (verifrogAbsPath: string) (tests: DeclTest list) : string =
    let sb = StringBuilder()
    let w (s: string) = sb.AppendLine(s) |> ignore
    let moduleName = toModuleName (Path.GetFileName(verifrogAbsPath))
    let fileName = Path.GetFileName(verifrogAbsPath)
    let genFileName = moduleName + ".g.fs"

    w $"// <auto-generated> from {fileName} — do not edit </auto-generated>"
    w $"module GeneratedTests.{moduleName}"
    w ""
    w "open Expecto"
    w "open Verifrog.Sim"
    w "open Verifrog.Runner.Declarative"
    w ""
    let tomlEsc = tomlAbsPath.Replace("\\", "/")
    w $"""let private config = Config.parse @"{tomlEsc}" """
    w ""
    w "[<Tests>]"
    w $"""let tests = testList "Declarative.{Path.GetFileNameWithoutExtension(fileName)}" ["""

    // Group by category
    let grouped =
        tests
        |> List.groupBy (fun t -> t.Category |> Option.defaultValue "Uncategorized")

    // Track output line number for #line reset (approximate, adjusted per test)
    for (cat, catTests) in grouped do
        w $"""    testList "{cat}" ["""
        for test in catTests do
            w $"""        testCase "{test.Name}" (fun () ->"""
            w $"            use sim = Sim.Create(config)"
            w $"            Sim.SuppressDisplay(true)"
            w $"            sim.Reset()"
            for ls in test.Steps do
                let stepExpr = renderStep ls.Step
                w (sprintf "# %d \"%s\"" ls.Line verifrogAbsPath)
                w $"""            executeStep sim ({stepExpr}) "{verifrogAbsPath}" {ls.Line}"""
            // Reset line numbering — use a high line number since we don't know exact generated line
            w (sprintf "#line 1000 \"%s\"" genFileName)
            w  "            ())"
        w  "    ]"

    w "]"
    sb.ToString()
