// verifrog_sim.cpp — Generic Verilator C shim for Verifrog
//
// Design-agnostic wrapper providing: create, destroy, reset, step,
// read/write signals by hierarchical name, checkpoint, restore.
//
// Signal access uses direct pointers discovered at init via Verilator's
// --public-flat-rw flag and scope/var enumeration API. This gives the
// same performance as khalkulo's hardcoded REG_ROOT macros, but works
// with any design.
//
// The model type is bound at compile time via verifrog_model.h,
// generated by `verifrog build`.
//
// Extracted from khalkulo's sim_shim.cpp, with all design-specific
// code (MAC accessors, weight SRAM, activation SRAM, register file)
// removed.

#include <cstdint>
#include <cstring>
#include <string>
#include <unordered_map>
#include <vector>
#include <mutex>
#include <cstdio>
#include <unistd.h>
#include <fcntl.h>

#include "verifrog_model.h"   // Generated: typedefs VerifrogModel, VerifrogModelRoot
#include "verilated.h"
#include "verilated_syms.h"   // VerilatedScopeNameMap, VerilatedVarNameMap

// Required by Verilator when not using SystemC
double sc_time_stamp() { return 0; }

// Override Verilator's default $stop handler to not abort the process.
static bool g_stop_warned = false;
void vl_stop(const char* filename, int linenum, const char* hier) {
    if (!g_stop_warned) {
        fprintf(stderr, "[verifrog] $stop at %s:%d — continuing (further $stop messages suppressed)\n",
                filename, linenum);
        g_stop_warned = true;
    }
}

// Global mutex — protects all sim operations since Verilator's global state
// (scope tables, VPI) and stdout redirection are not thread-safe.
// Tests running in parallel must serialize through this mutex.
static std::recursive_mutex g_sim_mutex;

// Display suppression globals
static bool g_suppress_display = true;
static int g_real_stdout_fd = -1;
static int g_devnull_fd = -1;

// Signal descriptor: direct pointer to data, bit width
struct SignalInfo {
    void* ptr;
    int bits;
    bool is_signed;
    const VerilatedVar* var;  // non-null for array vars (needed for indexed access)
};

// Force override entry
struct ForceEntry {
    std::string name;
    int64_t value;
};

// Simulation context
struct SimContext {
    VerilatedContext* vctx;
    VerifrogModel* model;
    uint64_t cycle_count;
    std::unordered_map<std::string, SignalInfo> signals;
    std::unordered_map<std::string, int64_t> forces;
};

// Checkpoint: raw copy of model root state
struct Checkpoint {
    std::vector<uint8_t> data;
    uint64_t cycle_count;
    size_t data_size;
};

// ---- Display suppression ----

static void suppress_init() {
    if (g_real_stdout_fd < 0) {
        g_real_stdout_fd = dup(STDOUT_FILENO);
        g_devnull_fd = open("/dev/null", O_WRONLY);
    }
}

static inline void eval_model(SimContext* ctx) {
    if (g_suppress_display) {
        std::lock_guard<std::recursive_mutex> lock(g_sim_mutex);
        suppress_init();
        fflush(stdout);
        dup2(g_devnull_fd, STDOUT_FILENO);
        ctx->model->eval();
        fflush(stdout);
        dup2(g_real_stdout_fd, STDOUT_FILENO);
    } else {
        ctx->model->eval();
    }
}

// ---- Signal discovery via Verilator scope/var API ----
// With --public-flat-rw, Verilator exposes all signals through
// VerilatedScope and VerilatedVar. We walk all scopes at init,
// building a map from user-friendly names to direct pointers.

static void register_signals(SimContext* ctx) {
    auto& m = ctx->signals;

    // Walk all registered scopes
    const VerilatedScopeNameMap* scopes = Verilated::scopeNameMap();
    if (!scopes) return;

    for (auto& [scope_name, scope_ptr] : *scopes) {
        // Get the var map for this scope
        const auto* vars = scope_ptr->varsp();
        if (!vars) continue;

        // Scope name is like "TOP.counter" — extract the part after "TOP."
        std::string scope_str(scope_name);
        std::string scope_prefix;
        size_t top_dot = scope_str.find('.');
        if (top_dot != std::string::npos) {
            // Skip "TOP." prefix, then find next dot for sub-modules
            std::string after_top = scope_str.substr(top_dot + 1);
            size_t next_dot = after_top.find('.');
            if (next_dot != std::string::npos) {
                // Sub-module: "TOP.counter.u_sub" -> prefix is "u_sub."
                scope_prefix = after_top.substr(next_dot + 1) + ".";
            }
            // Top-level module: no prefix (signals are just "count", "enable", etc.)
        }

        for (auto& [var_name, var_ptr] : *vars) {
            void* datap = var_ptr.datap();
            if (!datap) continue;

            int bits = var_ptr.entBits();
            if (bits <= 0) bits = 1;

            bool is_signed = var_ptr.isSigned();

            // Store pointer to the VerilatedVar for array indexing support
            const VerilatedVar* varp = &var_ptr;

            // Register with user-friendly name: "count", "u_sub.state", etc.
            // Don't override existing entries — the TOP scope's ports take
            // priority over sub-module internal copies (which Verilator
            // overwrites from ports during eval).
            std::string friendly_name = scope_prefix + std::string(var_name);
            if (m.find(friendly_name) == m.end()) {
                m[friendly_name] = { datap, bits, is_signed, varp };
            }

            // Also register with full path for explicit access
            std::string full_name = scope_str + "." + std::string(var_name);
            m[full_name] = { datap, bits, is_signed, varp };
        }
    }
}

// Parse trailing "[index]" from a name. Uses the LAST bracket pair,
// so "gen_bank[0].u_bank.mem[5]" parses as base="gen_bank[0].u_bank.mem", index=5.
static bool parse_array_index(const std::string& name, std::string& base, int& index) {
    size_t close = name.rfind(']');
    if (close == std::string::npos || close != name.size() - 1) return false;
    size_t bracket = name.rfind('[', close);
    if (bracket == std::string::npos) return false;
    base = name.substr(0, bracket);
    index = std::stoi(name.substr(bracket + 1, close - bracket - 1));
    return true;
}

// Resolve a signal name, supporting array indexing (e.g., "regs[42]").
// For plain names, looks up directly in the signal map.
// For indexed names, finds the base array var and computes the element pointer.
static bool resolve_signal(SimContext* ctx, const char* name, SignalInfo& out) {
    // Try direct lookup first
    auto it = ctx->signals.find(name);
    if (it != ctx->signals.end()) {
        out = it->second;
        return true;
    }

    // Try array indexing: "base_name[index]"
    std::string sname(name);
    std::string base;
    int index;
    if (parse_array_index(sname, base, index)) {
        auto base_it = ctx->signals.find(base);
        if (base_it != ctx->signals.end() && base_it->second.var) {
            const SignalInfo& base_sig = base_it->second;
            // Use VerilatedVar::datapAdjustIndex to get the element pointer.
            // DPI convention: dim=1 is the first unpacked dimension.
            // dim=0 is reserved for the packed dimension.
            void* elem_ptr = base_sig.var->datapAdjustIndex(
                base_sig.ptr, 1, index);
            if (elem_ptr) {
                out = { elem_ptr, base_sig.bits, base_sig.is_signed, base_sig.var };
                return true;
            }
        }
    }

    return false;
}

// Read a signal value through its direct pointer
static int64_t read_signal(const SignalInfo& sig) {
    if (sig.bits <= 8)  return *static_cast<uint8_t*>(sig.ptr);
    if (sig.bits <= 16) return *static_cast<uint16_t*>(sig.ptr);
    if (sig.bits <= 32) return *static_cast<uint32_t*>(sig.ptr);
    return *static_cast<int64_t*>(sig.ptr);
}

// Write a signal value through its direct pointer
static void write_signal(const SignalInfo& sig, int64_t value) {
    if (sig.bits <= 8)  { *static_cast<uint8_t*>(sig.ptr)  = (uint8_t)value; return; }
    if (sig.bits <= 16) { *static_cast<uint16_t*>(sig.ptr) = (uint16_t)value; return; }
    if (sig.bits <= 32) { *static_cast<uint32_t*>(sig.ptr) = (uint32_t)value; return; }
    *static_cast<int64_t*>(sig.ptr) = value;
}

// Apply all active force overrides
static void apply_forces(SimContext* ctx) {
    for (auto& [name, value] : ctx->forces) {
        auto it = ctx->signals.find(name);
        if (it != ctx->signals.end()) {
            write_signal(it->second, value);
        }
    }
    if (!ctx->forces.empty()) eval_model(ctx);
}

// ============================================================
// Extern "C" API for F# P/Invoke
// ============================================================

extern "C" {

SimContext* sim_create() {
    std::lock_guard<std::recursive_mutex> lock(g_sim_mutex);
    auto* ctx = new SimContext();
    ctx->vctx = new VerilatedContext();
    ctx->vctx->commandArgs(0, (const char**)nullptr);
    ctx->model = new VerifrogModel(ctx->vctx);
    ctx->cycle_count = 0;

    // Initial eval to populate Verilator's scope tables
    ctx->model->eval();

    // Discover all signals
    register_signals(ctx);

    return ctx;
}

void sim_destroy(SimContext* ctx) {
    std::lock_guard<std::recursive_mutex> lock(g_sim_mutex);
    if (!ctx) return;
    delete ctx->model;
    delete ctx->vctx;
    delete ctx;
}

void sim_reset(SimContext* ctx, int cycles) {
    std::lock_guard<std::recursive_mutex> lock(g_sim_mutex);
    if (!ctx) return;

    auto clk_it = ctx->signals.find("clk");
    auto rst_it = ctx->signals.find("rst_n");

    if (clk_it == ctx->signals.end() || rst_it == ctx->signals.end()) {
        fprintf(stderr, "[verifrog] WARNING: clk or rst_n not found. "
                "Ensure your top module has clk and rst_n ports.\n");
        return;
    }

    // Assert reset
    write_signal(rst_it->second, 0);
    write_signal(clk_it->second, 0);

    for (int i = 0; i < cycles; i++) {
        write_signal(clk_it->second, 0);
        eval_model(ctx);
        write_signal(clk_it->second, 1);
        eval_model(ctx);
    }

    // Release reset
    write_signal(rst_it->second, 1);

    // Extra cycles for reset synchronizers
    for (int i = 0; i < 4; i++) {
        write_signal(clk_it->second, 0);
        eval_model(ctx);
        write_signal(clk_it->second, 1);
        eval_model(ctx);
    }

    ctx->cycle_count = 0;
}

void sim_step(SimContext* ctx, int n) {
    if (!ctx) return;

    auto clk_it = ctx->signals.find("clk");
    if (clk_it == ctx->signals.end()) return;

    for (int i = 0; i < n; i++) {
        write_signal(clk_it->second, 0);
        eval_model(ctx);
        apply_forces(ctx);
        write_signal(clk_it->second, 1);
        eval_model(ctx);
        apply_forces(ctx);
        ctx->cycle_count++;
    }
}

uint64_t sim_get_cycle(SimContext* ctx) {
    return ctx ? ctx->cycle_count : 0;
}

// Read a signal by hierarchical name. Supports array indexing: "regs[42]".
// Returns 0 on success, -1 on error.
int sim_read(SimContext* ctx, const char* name, int64_t* out_value) {
    if (!ctx || !name || !out_value) return -1;

    SignalInfo sig;
    if (!resolve_signal(ctx, name, sig)) return -1;

    *out_value = read_signal(sig);
    return 0;
}

// Write a signal by hierarchical name. Supports array indexing: "regs[42]".
// Returns 0 on success, -1 on error.
int sim_write(SimContext* ctx, const char* name, int64_t value) {
    if (!ctx || !name) return -1;

    SignalInfo sig;
    if (!resolve_signal(ctx, name, sig)) return -1;

    write_signal(sig, value);
    eval_model(ctx);
    return 0;
}

// Get signal bit width. Returns -1 if not found.
int sim_signal_bits(SimContext* ctx, const char* name) {
    if (!ctx || !name) return -1;
    SignalInfo sig;
    if (!resolve_signal(ctx, name, sig)) return -1;
    return sig.bits;
}

// Total number of registered signals (unique by friendly name)
int sim_signal_count(SimContext* ctx) {
    return ctx ? (int)ctx->signals.size() : 0;
}

// Get signal name by index (for enumeration from F#)
int sim_signal_name(SimContext* ctx, int index, char* name_buf, int buf_len) {
    if (!ctx || index < 0 || index >= (int)ctx->signals.size()) return -1;
    auto it = ctx->signals.begin();
    std::advance(it, index);
    int len = (int)it->first.size();
    if (name_buf && buf_len > len) {
        std::memcpy(name_buf, it->first.c_str(), len + 1);
    }
    return len;
}

// Suppress/show $display output during eval()
void sim_suppress_display(int suppress) {
    g_suppress_display = (suppress != 0);
}

// ---- Checkpoint / Restore ----
// Uses memcpy of the root model struct. Works for designs where Verilator
// inlines all state into the root. For generate-array designs, see docs.

Checkpoint* sim_checkpoint(SimContext* ctx) {
    if (!ctx) return nullptr;

    auto* cp = new Checkpoint();
    auto* rootp = ctx->model->rootp;

    cp->data_size = sizeof(VerifrogModelRoot);
    cp->data.resize(cp->data_size);
    std::memcpy(cp->data.data(), rootp, cp->data_size);
    cp->cycle_count = ctx->cycle_count;

    return cp;
}

int sim_restore(SimContext* ctx, Checkpoint* cp) {
    if (!ctx || !cp) return -1;

    auto* rootp = ctx->model->rootp;
    std::memcpy(rootp, cp->data.data(), cp->data_size);
    ctx->cycle_count = cp->cycle_count;

    eval_model(ctx);
    return 0;
}

void sim_checkpoint_free(Checkpoint* cp) {
    delete cp;
}

uint64_t sim_checkpoint_cycle(Checkpoint* cp) {
    return cp ? cp->cycle_count : 0;
}

// ---- Signal forcing ----

int sim_force(SimContext* ctx, const char* name, int64_t value) {
    if (!ctx || !name) return -1;

    SignalInfo sig;
    if (!resolve_signal(ctx, name, sig)) return -1;

    ctx->forces[name] = value;

    // Apply immediately
    write_signal(sig, value);
    eval_model(ctx);
    return 0;
}

int sim_release(SimContext* ctx, const char* name) {
    if (!ctx || !name) return -1;
    return ctx->forces.erase(name) > 0 ? 0 : -1;
}

void sim_release_all(SimContext* ctx) {
    if (ctx) ctx->forces.clear();
}

int sim_force_count(SimContext* ctx) {
    return ctx ? (int)ctx->forces.size() : 0;
}

} // extern "C"
